<div class="uk-width-1-1 uk-padding-small uk-padding-remove-top">
  <h2>Upravit data akce</h2>
</div>
<div class="uk-width-1-2 uk-padding-small">
  <form class="" method="post">
    <div class="uk-margin-small">
      <label for="zacatek">Datum začátku</label>
      <input class="uk-input" id="zacatek" type="date" name="zacatek" value="<?= date("Y-m-d", strtotime($akce["zacatek"])) ?>">
    </div>
    <div class="uk-margin-small">
      <label for="konec">Datum konce</label>
      <input class="uk-input" id="konec" type="date" name="konec" value="<?= date("Y-m-d", strtotime($akce["konec"])) ?>">
    </div>
    <div class="uk-margin-small">
      <label for="nazev">Název akce</label>
      <input class="uk-input" id="nazev" type="text" name="nazev" value="<?= $akce["nazev"] ?>">
    </div>
    <div class="uk-margin-small">
      <label for="popis">Popis</label>
      <input class="uk-input" id="popis" type="text" name="popis" value="<?= $akce["popis"] ?>">
    </div>

    <div class="uk-width-1-1 uk-margin-small">
      <label for="komu">Vedoucí akce</label>
      <div class="uk-form-controls">
        <select class="uk-select" id="komu" name="vedouci_akce">
          <option> - Vyberte - </option>
          <?php
            $vedouci = DB::vsichniVedouci();
            foreach($vedouci as $v){
              if($akce["vedouci_akce"] == $v["id_vedouciho"])
                echo "<option value='".$v["id_vedouciho"]."' selected>".$v["jmeno"]." ".$v["prijmeni"]."</option>" ;
              else
                echo "<option value='".$v["id_vedouciho"]."' >".$v["jmeno"]." ".$v["prijmeni"]."</option>" ;
            }
           ?>
        </select>
    </div>
    </div>

    <p class="uk-text-right">
        <a class="btn-orange" href="/akce">Zrušit</a>
        <input type="submit" class="btn-green" name="upravit-akci" value="Upravit akci">
    </p>
  </form>
</div>
