<div class="uk-text-center">
  <h1>Aplikace Teepee</h1>
  <!--<img class="uk-card uk-card-default" src="/view/img/teepee-scrn.png" alt="Teepee desktop">-->
  <p>Dostupné pro Windows 10 a již brzy i pro Android</p>
</div>
<div class="uk-text-center uk-padding">
  <a href="/direct/teepee-windows/teepee-win32-ia32.zip" class="btn-orange"><span uk-icon="download"></span> Stáhnout pro Windows 10</a>
  
</div>
<div class="uk-width-1-1 uk-background-muted">
  <div class="uk-width-1-2 uk-margin-auto uk-padding">
    <h2>Instalace (Windows 10)</h2>
    <h3>1. Stáhněte soubor 'teepee-win32-ia32.zip' (odkaz výše)</h3>
    <h3>2. Stažený archiv rozbalte do Vámi zvolené složky</h3>
    <h3>3. Spouštějte dvojklikem na soubor 'teepee.exe'</h3>
    <h3>4. (volitelné) Můžete vytvořit zástupce souboru 'teepee.exe' a ten umístit na Vámi zvolené místo (např.plocha)</h3>
  </div>
</div>
