<div class="uk-height-1-1">
    <form class=" uk-position-center uk-width-1-4 uk-border-rounded" method="post">
        <img src="/view/img/logo_dark.png" alt="Royal Rangers" style="max-height:40px;">
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon" uk-icon="icon: user"></span>
                <input class="uk-input" type="text" name="jmeno">
            </div>
        </div>
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
                <input class="uk-input" type="password" name="heslo">
            </div>
        </div>
        <button class="btn-green uk-width-1-1" type="submit">Přihlásit se</button>
        <p class=" uk-text-center uk-text-small uk-margin-remove"><a href="/login/lost-password">zapomněl jsem heslo</a></p>
        <p class=" uk-text-center uk-text-small">nebo</p>
        <a href="/statistika" class="btn-blue uk-width-1-1 uk-text-small uk-text-center">Zobrazit statistiku</a>
    </form>

</div>