<div class="uk-height-1-1">
    <form class=" uk-position-center uk-width-1-4 uk-border-rounded" method="post">
        <img src="/view/img/logo_dark.png" alt="Royal Rangers" style="max-height:40px;">
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon" uk-icon="icon: user"></span>
                <input class="uk-input" type="text" name="uz-jmeno" placeholder="Uživatelské jméno">
            </div>
        </div>
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: mail"></span>
                <input class="uk-input" type="email" name="email" placeholder="Registrovaný email">
            </div>
        </div>
        <button class="btn-green uk-width-1-1" type="submit">Resetovat heslo</button>
        <p class=" uk-text-center uk-text-small uk-margin-remove"><a href="/login">zpět</a></p>

        
    </form>

</div>