<h1 class="uk-position-center uk-text-center">Under construction<br>:(</h1>
<!--<form method="post">
  <div class="uk-margin">
    <a onclick="pridejVsechnyEmaily()" class="btn-orange">Všichni</a>
  </div>

  <div class="uk-margin">
    <div class="uk-inline uk-width-1-1">
      <span class="uk-form-icon" uk-icon="icon: users"></span>
      <input class="uk-input" type="text" placeholder="Komu" name="to" id="to">
    </div>
  </div>

  <div class="uk-margin">
    <div class="uk-inline uk-width-1-1">
      <span class="uk-form-icon" uk-icon="icon: pencil"></span>
      <input class="uk-input" type="text" placeholder="Předmět" name="sub">
    </div>
  </div>

  <div class="uk-margin uk-height-1-1">
    <div class="uk-inline uk-width-1-1">
      <textarea id="tinyMCE" name="text"></textarea>
    </div>
  </div>
  <input type="submit" name="odeslat" value="Odeslat" class="btn-green">
  <input type="hidden" value="<?= $emailyAll ?>" name="emailyAll" id="emailyAll">
</form>

<script type="text/javascript">
  function pridejVsechnyEmaily(){
    document.getElementById("to").value = document.getElementById("emailyAll").value;
  }
</script>
-->