<div class="uk-height-1-1">
    <form class=" uk-position-center uk-width-1-4 uk-border-rounded" method="post">
        <img src="/view/img/logo_dark.png" alt="Royal Rangers" style="max-height:40px;">
        <h3 class="uk-margin-small">Reset hesla</h3>
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon" uk-icon="icon: lock"></span>
                <input class="uk-input" type="password" name="nove_heslo" placeholder="Nové heslo">
            </div>
        </div>
        <div class="uk-margin">
            <div class="uk-inline">
                <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
                <input class="uk-input" type="password" name="nove_heslo_znovu" placeholder="Nové heslo znovu">
            </div>
        </div>
        <button class="btn-green uk-width-1-1" type="submit" name="reset_hesla">Potvrdit nové heslo</button>
        <p class=" uk-text-center uk-text-small uk-margin-remove"><a href="/login">zrušit</a></p>

        
    </form>

</div>