<!-- Skryje upozornění po 2.5 vteřinách -->
<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('#alertbox').hide();
    }, <?= $user_config->upozorneni->skrytPo ?> * 1000);
  });
</script>
<script src="/view/js/main.js"></script>



<!-- Progressive webapp -->
<script>
window.addEventListener("load", () => {
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.register("/view/js/service-worker.js");
  }
});
</script>
<!-- push notifikace -->
<script>
  navigator.serviceWorker.ready.then(function(registration) {
  if (!registration.pushManager) {
    alert('Nepodporujete push notifikace !');
    return false;
  }
  //To subscribe `push notification` from push manager
  registration.pushManager.subscribe({
  userVisibleOnly: true //Always show notification when received
  })
  .then(function (subscription) {
  console.log('Subscribed.');
  })
  .catch(function (error) {
  console.log('Subscription error: ', error);
  });
})
</script>
<!-- install prompt -->
<script>
  window.addEventListener('beforeinstallprompt', e => {
  console.log('beforeinstallprompt Event fired');
  e.preventDefault();
  // Stash the event so it can be triggered later.
  this.deferredPrompt = e;
  return false;
  });
// When you want to trigger prompt:
this.deferredPrompt.prompt();
  this.deferredPrompt.userChoice.then(choice => {
  console.log(choice);
  });
this.deferredPrompt = null;
</script>