<meta charset="utf-8">
<title>Royal Rangers</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/view/uikit/css/uikit.min.css" />
<link rel="stylesheet" href="/view/css/main.css">
<script src="/view/uikit/js/uikit.min.js"></script>
<script src="/view/uikit/js/uikit-icons.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" charset="utf-8"></script>
<script src="https://cdn.tiny.cloud/1/a6opw39c17wwfw3no1lxla6ja60kvcd9e6837jbuwko9cfn2/tinymce/5/tinymce.min.js" referrerpolicy="origin"/></script>
<script>
    tinymce.init({
    selector: '#tinyMCE',
    plugins: 'lists  media  table ',
    height : "480"
    });
  </script>
<link rel="shortcut icon" href="view/img/favicon.ico" type="image/x-icon">
<!-- ChartJS -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.css">
<meta name="theme-color" content="#159957">
